name: 'MtnDev: Clean up Preview Deployments artifacts'
description: 'Cleans up preview deployments artifacts'

inputs:
  github-token:
    description: 'GitHub token'
    required: true
  doppler-token:
    description: 'Doppler token'
    required: true
  pr-number:
    description: 'Pull request number'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Log in to GitHub Container Registry
      run: echo "${{ inputs.github-token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      shell: bash

    - name: Pull clean-up image
      run: docker pull ghcr.io/high-country-dev/clean-up-preview-deployment:latest
      shell: bash

    - name: Run container
      run: |
        docker run --rm \
          -e GITHUB_TOKEN=${{ inputs.github-token }} \
          -e DOPPLER_TOKEN=${{ inputs.doppler-token }} \
          ghcr.io/high-country-dev/clean-up-preview-deployment:latest
      shell: bash
