name: Publish Clean Up Preview Deployment Action

on:
  push:
    branches:
      - feat/adding-environment-config
    # branches:
    #   - feat/adding-environment-config
    # paths:
    #   - actions/clean-up-preview-deployment/**
    #   - Dockerfile.clean-up-preview-deployment-action
    #   - .github/workflows/create-clean-up-preview-deployment-action-docker-image.yml

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/clean-up-preview-deployment
          docker build -f Dockerfile.clean-up-preview-deployment-action -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ steps.vars.outputs.sha_short }} .
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ steps.vars.outputs.sha_short }}
